### ISSUE TITLE
Minerva vulnerability?

### ISSUE THREAD

**Issue by tomato42** [ANSSI-FR/libecc#10]
Are you aware of the [minerva](https://minerva.crocs.fi.muni.cz/) attack? is libecc vulnerable?

**Comment by rb-anssi** [comment]
Hi @tomato42,

Thanks for the report and for your interest/concern about libecc!

Yes we are aware of the Minerva class of vulnerabilities, and in short yes libecc is vulnerable to this class of attacks *as is*, but see below (trivially and to be brief, we use non-complete formulas and our double and add always loop is not constant time with regards to the length of the scalar). However, libecc with BLINDING=1 makes use of scalar and point blinding that thwart such kind of attacks, and other similar attacks such as ROHNP (see the discussion here in the documentation: https://github.com/ANSSI-FR/libecc#signature-algorithm-blinding). It could be argued that BLINDING=1 should be used as default for security reasons, but as discussed in the pointed section we want to leave the choice to the end user to activate or not protections depending on the usage and the security context (since the countermeasures have performance impacts).

On a side note, a recent pull request #8 has introduced complete formulas whose integration are a current work in progress: such formulas will help to have a constant time loop in double and add always and get rid of Minerva timing attack. However, it is important to understand that this is not sufficient for a security critical usage/context, and BLINDING=1 will still have to be used (among other things to bring some protection against ROHNP and other side channel attacks).

Regards,

**Comment by tomato42** [comment]
I'm not sure if blinding will help: Minerva is only about guessing the nonce, and then from that getting the private key. It works even if your double and add instructions are completely side-channel free and you use them in a Montgomery ladder. It depends on the nonce not having the same bit size every time (which it won't if it is selected uniformly at random). Are you blinding the private key or both the private key and the nonce?

Also the mitigation is trivial and has minimal performance impact (unlike blinding), see Conclusion section in https://eprint.iacr.org/2011/232

**Comment by rb-anssi** [comment]
Hi,

BLINDING=1 in libecc activates both scalar (i.e. nonces) blinding as well as private key blinding. Minerva is about guessing the MSB of the nonces and using them as an oracle to construct a HNP instance. 
Agreed that the blinding does not remove the timing side channel, however it mitigates the Hidden Number Problem based attacks since the attacker does not have an oracle modulo q (the order of the curve) anymore. Let k be the nonce, blinding computes the scalar multiplication using k'=k+(r*q) where r is random in [0, q[, so that k' is in the [0, q*q[ interval. The timing side channel the attacker will have using Minerva will be on k' MSB, but the equations ECDSA provides using known (r, s) are modulo q, and the HNP problem instance does not hold anymore. 
As a side note, other forms of "blinding" such as scalar random splitting (i.e. split k = k1 + k2, with random k1 in [0, q[ and k2 = k - k1 in [0, q[) are indeed not a mitigation against Minerva since the timing side channels on k1 and k2 will keep the HNP instance true.

Adding a small multiple of the curve order as proposed in https://eprint.iacr.org/2011/232 is surely a quick fix for the timing side channel per se, but as noted by the authors themselves this does not cover other microarchitectural/other side channel attacks (e.g. cache/branch prediction based and so on, see ). Scalar blinding brings some robustness against such attacks (albeit not bulletproof), this is why we consider BLINDING=1 as a "must use" in use cases where there is a doubt about possible attacks (local or remote, using basic or advanced side channels).

Finally, since we plan to move to complete formulas as the default ones to be used quite soon, we hope to naturally get rid of the timing side channel on the nonce as a clean solution.

Regards,

**Comment by tomato42** [comment]
ok, thanks for the detailed explanation. You can close the issue if you think it does not require any specific action

**Comment by rb-anssi** [comment]
Thanks for your feedback.
As previously discussed, the complete formulas have been fully integrated with commit 442b747, so now the double and add always loop is performed in constant time with regard to the scalar length. This should mitigate Minerva (as a complementary countermeasure to blinding), and closes the issue.

Regards,

**Comment by rb-anssi** [comment]
Commit f81ba63 should close this issue as the countermeasure of adding a small multiple of the curve order has been implemented for all the signature schemes when incomplete formulas and no blinding are explicitly chosen by the user.
