### ISSUE TITLE
rand does not include Wincrypt.h

### ISSUE THREAD

**Issue by GoodiesHQ** [ANSSI-FR/libecc#12]
When building on Cygwin for windows, I had to do the following modification to get it to compile properly `CC=gcc CFLAGS="-include 'Wincrypt.h'" make`

Simply doing `CC=gcc make` will result in a lot of invalid types due to the missing header file. I think just adding `#include <wincrypt.h>` within `rand.h` should be sufficient.

https://i.imgur.com/FvkgffY.png

**Comment by rb-anssi** [comment]
Hi,

This is weird since Cygwin is supposed to expose a POSIX API, and hence the `#if defined(WITH_STDLIB) && (defined(__unix__) || defined(__APPLE__))` code is supposed to be compiled in `rand.c`: you should not have `wincrypt.h`related issues since such headers should not be used.

I have tested the project with Cygwin 3.1.2 under Windows 7, and the it compiles with exported `LDFLAGS=" "`.

Can you please provide more details about your compilation environment?

Thanks,
