### ISSUE TITLE
secp256k1

### ISSUE THREAD

**Issue by orlandofernandez** [ANSSI-FR/libecc#24]
Hello, I am new to the lib, that I find fantastic. However running curve_basic_examples, all curves work except secp256k1. It just stays there. Is the pb on the def of the curve? Thank you!

**Comment by rb-anssi** [comment]
Hi @orlandofernandez,

Well spotted indeed. This issue concerns the pathological case where the point at infinity is reached for this secp256k1 curve particularly. The way the side-channel countermeasure for point at infinity is handled is the root cause of this "stall" (an endless loop assert is reached because of a division by zero).

Actually, this issue has been handled and is fixed on the branch ecdh (https://github.com/ANSSI-FR/libecc/tree/ecdh) in commit https://github.com/ANSSI-FR/libecc/commit/1634c53d7d0df56a666d6fd19b3a1509d720f97a on the file `src/curves/prj_pt.c` (https://github.com/ANSSI-FR/libecc/commit/1634c53d7d0df56a666d6fd19b3a1509d720f97a#diff-a08e02cbc7a5f4de87dfd0fe4cadd10c604b0938e6cb17196b3d3877474ea28c).

This branch is about to be merged with master shortly. You can either use this branch (that is considered stable), wait for the merge, back port the patch, or deal with the pathological case (if it is not reached) in your examples. Of course, for production code we strongly advise to wait for the merge that will come very soon :-)

Regards,

**Comment by rb-anssi** [comment]
Closed by PR merge ad4ac13a1a5711198fedf59cecc7591102669184
